---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  selector:
    matchLabels:
      app: be-apps
  replicas: 2
  template:
    metadata:
      labels:
        app: be-apps
    spec:
      containers:
      - name: be
        image: iansinambela/li-be:latest
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.25"
            memory: "700Mi"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  selector:
    app: be-apps
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32100
